[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ws_medical_private_record = "6c5BjmuitDUaeQjzsdszGtiAbMmiRB7zv44qmTbaqsE1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/air/.config/solana/local.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
[test]
startup_wait = 60000
[test.validator]
[[test.genesis]]
address = "F3G6Q9tRicyznCqcZLydJ6RxkwDSBeHWM458J7V6aeyk"
program = "/Users/air/Documents/programmingwork/blockchain/solana/arcium/ws_medical_private_record/artifacts/arcium_program_0.5.4.so"
[[test.genesis]]
address = "L2TExMFKdjpN9kozasaurPirfHy9P8sbXoAN1qA3S95"
program = "artifacts/lighthouse.so"

[[test.validator.account]]
address = "EQr6UCd7eyRjpuRsNK6a8WxkgrpSGctKMFuz92FRRh63"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "BSC6rWJ9ucqZ6rcM3knfpgdRwCyJ7Q9KsddjeSL4EdHq"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "Ax3s6bJdJrv9wSS88q4CW5Axchzzm9yiXEmmRkNxmLx6"
filename = "artifacts/wallet_acc_Ax3s_mLx6.json"

[[test.validator.account]]
address = "57wZXDfjocLMhc9GvqWE1ceyt8eFFA3M6pYXFe1zPLM5"
filename = "artifacts/arx_ata_Ax3s_mLx6.json"

[[test.validator.account]]
address = "RY8od5N92rrDQUkAKWcxhMCKGrjTG8dhwE2uiiAPRSx"
filename = "artifacts/wallet_acc_RY8o_PRSx.json"

[[test.validator.account]]
address = "6CBTxA2PbySQenGWwPJDgYBSrzw3GPJqmv9jbVtgR7is"
filename = "artifacts/wallet_acc_callback_6CBT_R7is.json"

[[test.validator.account]]
address = "GhdqzZVvonGdMMzoiTByfsKSKiEzru2fwbDTJffHhQma"
filename = "artifacts/arx_ata_RY8o_PRSx.json"

[[test.validator.account]]
address = "9wjkDyZy3cJnACL72iLsgazwWcNBwQaHF3CpxZY2yxzU"
filename = "artifacts/operator_acc_RY8o_PRSx.json"

[[test.validator.account]]
address = "9CaJVqHPWPGRDY1x7Eew5a3BuTcCYm8JQXmk8coE1Zkf"
filename = "artifacts/arx_node_RY8o_PRSx.json"

[[test.validator.account]]
address = "CY9oUpvXYZ3ztJy2dJXiVzkZsSjWpt6KGJ45ft3jRcPi"
filename = "artifacts/wallet_acc_CY9o_RcPi.json"

[[test.validator.account]]
address = "ComRnuj1oZDt1rtQHoeAv1qVQ6h6WoqQ81Tt9Z7FP1Zy"
filename = "artifacts/wallet_acc_callback_ComR_P1Zy.json"

[[test.validator.account]]
address = "Gwx9cNujHb6RZShu3AGwXZpV6MJav16eXqFr1C3bZdTE"
filename = "artifacts/arx_ata_CY9o_RcPi.json"

[[test.validator.account]]
address = "3bcckfi3Uf4GHMHPu9c25qoXDeY5LssSYRkihjQWQPLk"
filename = "artifacts/operator_acc_CY9o_RcPi.json"

[[test.validator.account]]
address = "HwMdVdMkep2njXpEVZmWrbYPtsGdpJJvZzSb673YMZBy"
filename = "artifacts/arx_node_CY9o_RcPi.json"

[[test.validator.account]]
address = "3kMQur1kfAYp5JeoXRq11CUnP5x8DT5dw12rHnfoJNPg"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "Hh789mQvkJs6RKRTDfm6vcFp5xims6wzJMUfK4ZiqPoM"
filename = "artifacts/private_record_lookup_raw_circuit_0.json"

[[test.validator.account]]
address = "9rjsSUinjj9961Ea6PjobXhaFsu2a1bqW7wkLZXKf1JU"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "DMEXkcxunrDQcZj6fSmh5xCFxUQVViD8etBdk3ucMFQR"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "EHmdacJi9fyWmBC5ChHSLVmW7jaqpdE51Urh3Yoz8ukH"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "RJ56J5zMy5yXFYcWHjcQfdT2f2PQAGMom7UMyHw3kkj"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "8dZouGFqvrkVS6wgzwynwvQNvnHqPdyi8Eq1Zm6z4KSi"
filename = "artifacts/executing_pool_acc.json"
